require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CategoryPostsController do

  # This should return the minimal set of attributes required to create a valid
  # CategoryPost. As you add validations to CategoryPost, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all category_posts as @category_posts" do
      category_post = CategoryPost.create! valid_attributes
      get :index
      assigns(:category_posts).should eq([category_post])
    end
  end

  describe "GET show" do
    it "assigns the requested category_post as @category_post" do
      category_post = CategoryPost.create! valid_attributes
      get :show, :id => category_post.id.to_s
      assigns(:category_post).should eq(category_post)
    end
  end

  describe "GET new" do
    it "assigns a new category_post as @category_post" do
      get :new
      assigns(:category_post).should be_a_new(CategoryPost)
    end
  end

  describe "GET edit" do
    it "assigns the requested category_post as @category_post" do
      category_post = CategoryPost.create! valid_attributes
      get :edit, :id => category_post.id.to_s
      assigns(:category_post).should eq(category_post)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CategoryPost" do
        expect {
          post :create, :category_post => valid_attributes
        }.to change(CategoryPost, :count).by(1)
      end

      it "assigns a newly created category_post as @category_post" do
        post :create, :category_post => valid_attributes
        assigns(:category_post).should be_a(CategoryPost)
        assigns(:category_post).should be_persisted
      end

      it "redirects to the created category_post" do
        post :create, :category_post => valid_attributes
        response.should redirect_to(CategoryPost.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved category_post as @category_post" do
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryPost.any_instance.stub(:save).and_return(false)
        post :create, :category_post => {}
        assigns(:category_post).should be_a_new(CategoryPost)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryPost.any_instance.stub(:save).and_return(false)
        post :create, :category_post => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested category_post" do
        category_post = CategoryPost.create! valid_attributes
        # Assuming there are no other category_posts in the database, this
        # specifies that the CategoryPost created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CategoryPost.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => category_post.id, :category_post => {'these' => 'params'}
      end

      it "assigns the requested category_post as @category_post" do
        category_post = CategoryPost.create! valid_attributes
        put :update, :id => category_post.id, :category_post => valid_attributes
        assigns(:category_post).should eq(category_post)
      end

      it "redirects to the category_post" do
        category_post = CategoryPost.create! valid_attributes
        put :update, :id => category_post.id, :category_post => valid_attributes
        response.should redirect_to(category_post)
      end
    end

    describe "with invalid params" do
      it "assigns the category_post as @category_post" do
        category_post = CategoryPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryPost.any_instance.stub(:save).and_return(false)
        put :update, :id => category_post.id.to_s, :category_post => {}
        assigns(:category_post).should eq(category_post)
      end

      it "re-renders the 'edit' template" do
        category_post = CategoryPost.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CategoryPost.any_instance.stub(:save).and_return(false)
        put :update, :id => category_post.id.to_s, :category_post => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested category_post" do
      category_post = CategoryPost.create! valid_attributes
      expect {
        delete :destroy, :id => category_post.id.to_s
      }.to change(CategoryPost, :count).by(-1)
    end

    it "redirects to the category_posts list" do
      category_post = CategoryPost.create! valid_attributes
      delete :destroy, :id => category_post.id.to_s
      response.should redirect_to(category_posts_url)
    end
  end

end
